# Generated by Django 5.2 on 2025-06-09 13:05

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='time_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('morning', '6 - 12h'), ('afternoon', '12 - 18h'), ('evening', '18 - 0h'), ('late', '0h - 6h')], max_length=100),
        ),
    ]
