# Generated by Django 5.2 on 2025-05-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_candidateprofile_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='verification_documents',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
    ]
