# Generated by Django 5.2 on 2025-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_company_image_companyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv_custom',
            field=models.FileField(blank=True, null=True, upload_to='cvs_custom/'),
        ),
    ]
